### ISSUE TITLE
dhcpcd is enabled on live boot and after installation

### ISSUE THREAD

**Issue by RubenKelevra** [Apricity-OS/apricity-build#124]
On my notebook the dhcpcd@ensNsM service is started while doing a live boot and after installation. This seems a unsafe default since network-manager is running as well.

**Comment by agajews** [comment]
Which version of Apricity do you have running? This should have been fixed last month.

**Comment by RubenKelevra** [comment]
The latest stable release, yesterday on my notebook this bug still occurs. 
The boot stalls for several seconds and shows that systemd is waiting for 
dhcpcd@lan-interface. Since theres no LAN-cabled plugged in this is pretty 
useless. :)

**Comment by agajews** [comment]
That's very weird. Dhcpcd isn't ever explicitly enabled (as far as I can tell), and it doesn't like being disabled either ( #122 ).

**Comment by dealloc** [comment]
As a temporary work around you can stop dhcpd from running on your system by masking it (see #122)

**Comment by RubenKelevra** [comment]
Might be somehow related to nmbd.service or smbd.service which both try to start but crash at my installation...

**Comment by dealloc** [comment]
You can safely disable them, I am running with dhcpd, smbd and nmbd disabled for over a week now and I have yet to run into problems :)

**Comment by RubenKelevra** [comment]
I just tried to disable nmbd.service and smbd.service, and dhcpcd still tries to do dhcp :(

I know that I can mask the service, but I think we should try to locate the cause if this bug so I don't mask it currently :)

**Comment by RubenKelevra** [comment]
I've created a different ticket for the smbd/nmbd services:

https://github.com/Apricity-OS/apricity-build/issues/132
